### ISSUE TITLE
bad mirror URL in mirrorlist.txt

### ISSUE THREAD

**Issue by jx759** [iuscommunity/umirr#9]
The mirror URL related to mirrors.kernel.org is bad - returns 404.

For example I see the following mirrors.kernel.org URLs in mirrorslist.txt...

`/var/cache/yum/x86_64/6Server/ius/mirrorlist.txt`:
http://mirrors.kernel.org/ius/stable/Redhat/6/x86_64/

`/var/cache/yum/x86_64/7Server/ius/mirrorlist.txt`:
http://mirrors.kernel.org/ius/stable/CentOS/7/x86_64/

Yum will occasionally display:
`http://mirrors.kernel.org/ius/stable/Redhat/6/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"`

These kinds of errors are reported via `yum-cron` notifications as well.

AFAICT, looks like yum will use another mirror - so no indications that yum is not working.

**Comment by carlwgeorge** [comment]
We are in the middle of [switching from the mirror network to a CDN](https://github.com/iusrepo/infrastructure/issues/14).  Once you update your ius-release package as detailed in that issue, you won't be pointing to the CDN, and not be hitting the umirr application at all anymore.

Some of our former mirror network members still want to keep mirroring our content for their own purposes.  That new content doesn't match the paths returned by umirr, which is what is causing those broken links.  I have disabled those mirrors (including kernel.org) in umirr to avoid these broken links.
